server: 
  # 端口号
  port: 5000
  # 是否启用压缩
  compression: 
    enabled: true
  # tomcat配置
  tomcat: 
    uri-encoding: UTF-8

spring:
  mvc:
    favicon:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/health?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: root
    password: 724055
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
      
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: dev-redis
    # Redis服务器连接端口
    port: 6379
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 60000
  messages:
    encoding : UTF-8
    basename : i18n/messages

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.greatwall.business.db
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #驼峰下划线转换
    db-column-underline: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #原生配置
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId） 
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

mapper:
  mappers:
    - xingkong.db.mybatis.mapper.MybatisMapper
  not-empty: false
  identity: MYSQL
  style: camelhump
beetl:
  templatesPath : templates
  enabled : true